name: Approve Deploy PR

on:
  pull_request_target:
    types: [opened]
  

jobs:
  approve:
    name: Approve deploy pull request
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TEST_APP_ID }}
          private_key: ${{ secrets.TEST_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const reviewersData = await github.rest.pulls.listRequestedReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }).data;
            const reviewers = [...reviewersData.users, ...reviewersData.teams];
            github.rest.pulls.removeRequestedReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers
            })
            console.log(reviewers);
