name: Back merge
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  backmerge-master:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set Git config
        run: |
          git config --global user.email "hoklaam.cheng@gmail.com"
          git config --global user.name "Hok Laam Cheng"
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TEST_APP_ID }}
          private-key: ${{ secrets.TEST_APP_PRIVATE_KEY }}
      - name: Checkout staging
        uses: actions/checkout@v4
      - name: Merge master back to staging
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff origin/main -m "Auto-merge main back to staging"
      - name: Pushing to the protected branch 'staging'
        uses: CasperWA/push-protected@6b25de805895da731062c43da647425fbb383128 #v2.14
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: staging