name: Back merge
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  # Needed until staging deployments happen independently of production.
  backmerge-delay:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for master deploy
        run: |
          sleep 60
  backmerge-master:
    needs: [backmerge-delay]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set Git config
        run: |
          git config --global user.email "hoklaam.cheng@gmail.com"
          git config --global user.name "Hok Laam Cheng"
      - name: Checkout staging
        uses: actions/checkout@v2
        with:
          ref: staging
          token: ${{ secrets.PAT }}
      - name: Merge master back to staging
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff origin/main -m "Auto-merge main back to staging"
      - name: Pushing to the protected branch 'staging'
        uses: CasperWA/push-protected@6b25de805895da731062c43da647425fbb383128 #v2.14
        with:
          token: ${{ secrets.PAT }}
          branch: staging