name: Schedule Pull Request

on: workflow_dispatch

#   schedule:
#     - cron: '0 13 * * 1' # Every Monday at 1 PM

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TEST_APP_ID }}
          private_key: ${{ secrets.TEST_APP_PRIVATE_KEY }}

      - name: Run script to create pull request
        run: node create-pull-request.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}