name: Schedule Pull Request

on: workflow_dispatch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TEST_APP_ID }}
          private_key: ${{ secrets.TEST_APP_PRIVATE_KEY }}
      - name: Reset
        run: |
            git fetch origin staging:staging
            git reset --hard staging
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: weekly-deploy-${{ steps.date.outputs.date }}
          title: "Other(N/A): Weekly Deploy [${{ steps.date.outputs.date }}]"
          body: "Automated weekly deploy pull request"
          team-reviewers: platform-frontend-deployers
      # - name: Post Slack Message
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.26.0
      #   with:
      #     channel-id: 'C06DAKH58V7'
      #     payload: |
      #       {
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "@oncall-fin The weekly frontend deploy pull request has been created:\n*<${{steps.create_pr.outputs.pull-request-url}}|Link to Pull Request>*\nPlease follow the <https://stackadapt.atlassian.net/wiki/spaces/WEB/pages/2678882554/Platform+Production+Deploy+Workflow+-+Post+Migration|Platform Production Deploy Workflow> steps to deploy frontend production."
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}