name: Schedule Pull Request

on: workflow_dispatch
  # - schedule:
  #   - cron: '0 13 * * 1' # Every Monday at 1 PM

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TEST_APP_ID }}
          private_key: ${{ secrets.TEST_APP_PRIVATE_KEY }}
      - name: Reset
        run: |
            git fetch origin staging:staging
            git reset --hard staging
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: weekly-deploy-${{ steps.date.outputs.date }}
          title: "Other(N/A): Weekly Deploy [${{ steps.date.outputs.date }}]"
          body: "Automated weekly deploy pull request"
          team-reviewers: platform-frontend-deployers
      - name: Remove reviewers
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const { PR_NUMBER } = process.env;
            const owner = 'hoklaamc-personal';
            const repo = 'test-releases';
            const reviewers = await github.rest.pulls.listRequestedReviewers({
              owner,
              repo,
              pull_number: PR_NUMBER
            });
            console.log(reviewers.data.teams);
            const team_reviewers = reviewers.data.teams.map(team => team.name);
            github.rest.pulls.removeRequestedReviewers({
              owner,
              repo,
              pull_number,
              reviewers: reviewers.data.users,
              team_reviewers
            });