name: Deploy Staging

concurrency:
  group: test-staging-deployment
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [Staging Push CI]
    types: [completed]
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA (default: latest from master)'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.commit_sha || 'staging' }}
      - name: Deploy
        run: git rev-parse HEAD
  # on-failure:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Deploy failed due to failed staging push CI"
  #     - run: exit 1