name: Deploy Staging Alt

concurrency: test-staging-deployment

on:
  push:
    branches:
      - staging-alt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Deploy
        run: |
          echo "Deploy staging alt"