name: Deploy Main

concurrency: test-main-deployment

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA (default: latest from master)'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy
        run: |
          COMMIT_SHA=${{ github.sha }}
          if [ -n "${{ github.event.inputs.commit }}" ]; then
            COMMIT_SHA=${{ github.event.inputs.commit }}
          fi

          echo "Using commit SHA: $COMMIT_SHA"