name: Deploy Staging

concurrency:
  group: test-staging-deployment
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [Staging Push CI]
    types: [completed]
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA (default: latest from master)'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1
      - name: Checkout code
        uses: actions/checkout@master
      - name: Deploy
        run: |
          COMMIT_SHA=${{ github.sha }}
          if [ -n "${{ github.event.inputs.commit }}" ]; then
            COMMIT_SHA=${{ github.event.inputs.commit }}
          fi

          echo "Using commit SHA: $COMMIT_SHA"
  # on-failure:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Deploy failed due to failed staging push CI"
  #     - run: exit 1