name: Deploy Main

concurrency:
  group: test-main-deployment
  cancel-in-progress: true

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA (default: latest from master)'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.commit_sha || 'master' }}
      - name: Deploy
        run: git log --pretty=format:'%h' -n 1