name: Deploy Main

concurrency: test-main-deployment

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA (default: latest from master)'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.commit || 'main' }}
      - name: Deploy
        run: echo "${{ github.event.head_commit.committer.username }}"
