name: Deploy Staging

concurrency:
  group: test-staging-deployment
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [Staging Push CI]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@master
        with:
          ref: staging
      - name: Deploy
        run: git rev-parse HEAD