name: Deploy Main

concurrency:
  group: test-main-deployment
  cancel-in-progress: true

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA (default: latest from master)'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master
      - name: Deploy
        run: |
          COMMIT_SHA=${{ github.sha }}
          if [ ${{ github.event_name }} == "workflow_dispatch" ] && [ ${{ github.actor }} != "hoklaamc" ]; then
            echo "You do not have the permissions to manually trigger a deploy. Ask for assistance from an admin."
            exit 1
          fi

          if [ -n "${{ github.event.inputs.commit }}" ]; then
            COMMIT_SHA=${{ github.event.inputs.commit }}
          fi

          echo "Using commit SHA: $COMMIT_SHA"