name: Deploy Staging

concurrency: test-staging-deployment

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      commit:
        description: Commit SHA1
        required: true
        default: $GITHUB_SHA
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run post-deploy script
        run: |
          echo "Run deploy script. Commit: ${{ github.event.inputs.commit }}"