name: Deploy Main

concurrency: test-main-deployment

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA (default: latest from master)'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.commit || 'main' }}
      - name: Deploy
        run: echo "Pusher.name ${{ github.event.pusher.name }} Pusher.username ${{github.event.pusher.username}} Author.name ${{github.event.head_commit.author.name }} Author.username ${{github.event.head_commit.author.username}} Committer name ${{github.event.head_commit.committer.name }} Committer username ${{github.event.head_commit.committer.username }} Sender.name ${{github.event.sender.name}} Sender.login ${{github.event.sender.login}}"
