name: Deploy Staging

concurrency: test-staging-deployment

on:
  workflow_run:
    workflows: [Staging Push CI]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@master
        with:
          ref: staging
      - name: Deploy
        run: echo "Run deploy workflow with commit SHA :" $(git rev-parse HEAD)