# name: Deploy Staging

# concurrency: test-staging-deployment

# on:
#   push:
#     branches:
#       - staging
#   workflow_dispatch:
#     inputs:
#       commit:
#         description: Commit SHA1
#         required: true
#         default: "undefined"
#         type: string

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run post-deploy script
#         run: |
#           echo "Run deploy script. Commit: $GITHUB_SHA"

name: Deploy Staging

concurrency: test-staging-deployment

on:
  workflow_run:
    workflows: [Staging Push CI]
    types: [completed]
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA (default: latest from master)'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Deploy
        run: |
          COMMIT_SHA=${{ github.sha }}
          if [ -n "${{ github.event.inputs.commit }}" ]; then
            COMMIT_SHA=${{ github.event.inputs.commit }}
          fi

          echo "Using commit SHA: $COMMIT_SHA"
  on-failure:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy failed due to failed staging push CI"