name: On PR

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TEST_APP_ID }}
          private_key: ${{ secrets.TEST_APP_PRIVATE_KEY }}
      - uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          ENABLED_FOR_MANUAL_CHANGES: 'true'