name: Weekly deploy auto approve

on:
  pull_request:
    types: [opened]

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        if: github.actor == 'hok-personal-test-releases'
        with:
          review-message: "Auto approved automated PR"
          github-token: ${{ secrets.PAT }}
