name: Weekly deploy auto approve

on:
  pull_request:
    types: [opened]

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TEST_APP_ID }}
          private_key: ${{ secrets.TEST_APP_PRIVATE_KEY }}
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        if: github.actor == 'hok-personal-test-releases'
        with:
          review-message: "Auto approved automated PR"
          github-token: ${{ secrets.PAT }}
