name: Main Pull Request CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  required:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Test"
          exit 0
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Prettier"
          exit 0
  optional:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "E2E Test"
          exit 1
